# This is a basic workflow to help you get started with Actions

name: Terraform_destroy

# Controls when the workflow will run
on: workflow_dispatch
  # Triggers the workflow on push or pull request events but only for the main branch

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  terraform_destroy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    name: Destroy everything
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: infra

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: Terraform Init
        run: terraform init
      
      - name: Write env file
        run: echo "access_key = \"$AWS_ACCESS_KEY_ID\""  >> env.tfvars && echo -n "secret_key = \"$AWS_SECRET_ACCESS_KEY\"" >> env.tfvars
      
      - name: Terraform destroy
        run: terraform destroy --auto-approve -input=false -var-file env.tfvars
        